apiVersion: v1
kind: Pod
metadata:
  name: redis-sample-hp
spec:
  containers:
  - name: redis-sample-hp
    image: redis
    volumeMounts:
    - mountPath: /redis-hp
      name: redis-volume-hp
  volumes:
  - name: redis-volume-hp
    hostPath:
      # directory location on host
      path: /opt/k8s-examples/storage/hostpath/data-redis
      # this field is optional
      type: DirectoryOrCreate
