apiVersion: v1
kind: Pod
metadata:
  name: redis-sample
spec:
  containers:
  - name: redis-sample
    image: redis
    volumeMounts:
    - name: redis-storage-sample
      mountPath: /data/redis
  volumes:
  - name: redis-storage-sample
    emptyDir: {}
